language: java
install: true

jdk:
  - openjdk11

script:
  - cd backend && ./gradlew test

before_cache:
  - rm -f  $HOME/backend/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/backend/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/backend/.gradle/caches/
    - $HOME/backend/.gradle/wrapper/