name: dopplertask
version: 0.3.1
summary: Task automation
description: |
  Doppler is a revolutionary open-source software that allows you to automate tasks easily.
  Whether it’s a bunch of bash scripts or just starting your car remotely, you can automate it.
  Build, run, reuse and share automations with anyone around the globe.
confinement: devmode
base: core18

parts:
  doppler-api:
    plugin: gradle
    source: https://github.com/dopplertask/doppler
    source-type: git
    source-tag: v0.3.1
    source-subdir: backend
    gradle-options: [-xtest, build]
    gradle-output-dir: build/libs
  doppler:
    plugin: go
    source: https://github.com/dopplertask/doppler
    source-tag: v0.3.1
    source-subdir: cli
    source-type: git
    build-packages:
      - gcc

apps:
  doppler-api:
    command: java -jar $SNAP/jar/doppler-0.3.1.jar
    daemon: simple
    plugs:
      - network-bind
      - network-observe
  doppler:
    command: bin/cli
    aliases: [doppler]
